baseURL: "https://1code-xyz.github.io"
languageCode: "en-us"
title: "1code - Enjoy Life, Not Work"
theme: "theme"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  offices:
    - country: China
      address: Shanghai
      email: info@1code.xyz

  foundingMembers:
    - name: Samyro
      avatar: /images/samyro.jpeg
      github: samyro
      title: Chief Happiness Officer
    - name: Ciel
      avatar: /images/imwithye.png
      github: imwithye
      title: Wizard of Light Bulb Moments
